# Generated by Django 4.0.4 on 2022-09-14 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField()),
                ('time_and_date', models.DateTimeField(auto_now_add=True)),
                ('cut_off_time', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_and_date'],
            },
        ),
        migrations.CreateModel(
            name='ScannedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('student_id_num', models.CharField(max_length=10)),
                ('student_department', models.TextField()),
                ('student_course', models.TextField()),
                ('student_year', models.IntegerField()),
                ('student_block', models.CharField(max_length=5)),
                ('time_scanned', models.DateTimeField(auto_now_add=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='barcode_attendance.attendance')),
            ],
            options={
                'ordering': ['-time_scanned'],
            },
        ),
    ]
