# Generated by Django 4.0.4 on 2022-09-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScannedStudents',
            new_name='ScannedStudent',
        ),
    ]
